Repository civicrm/civicrm-dev-docs, pull requests merged in 2020-04, with the labels that each got.

#744 Resolve issue #742 by documenting new hook_civicrm_alterExternUrl
  docs/hooks/hook_civicrm_alterExternUrl.md
  docs/hooks/list.md
  mkdocs.yml
Labels: approved, needs: core release first

#772 Add in documentation of new alterUFFields Hook
  docs/hooks/hook_civicrm_alterUFFields.md
  docs/hooks/list.md
  mkdocs.yml
Labels: needs: core release first

#780 Document hook_civicrm_postCommit
  docs/hooks/changes.md
  docs/hooks/hook_civicrm_postCommit.md
  docs/hooks/list.md
  mkdocs.yml
Labels: needs: core release first

#734 update navigationMenu hook example to show use of 'attr' parameter
  docs/hooks/hook_civicrm_navigationMenu.md
Labels: priority: high

#798 Update docs about customising templates to mention CiviCRM Regions
  docs/framework/templates/customizing.md
Labels: approved
